config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: {
    sessions: 'player/sessions',
    registrations: 'player/registrations',
    passwords: 'player/passwords'
  }

  devise_for :teams, controllers: {
    sessions: 'team/sessions',
    registrations: 'team/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # player
  root 'player/home#about' # ネストしたコントローラに対してrootを設定する記述法
  namespace :player do
    resources :players, only: [:show, :edit, :update, :destroy] do
      get :exit, on: :member # idが必要なためmemberを使う
    end
    resources :teams, only: [:index, :show] do
      resources :contacts, only: [:new, :create] do
        get :complete, on: :collection # idがないからcollectionを使う
      end
      resource :bookmarks, only: [:create, :destroy] # この２つはid不要。
    end
    resources :bookmarks, only: [:index] # 上に混ぜるとpathが消えるので分けた。
    resources :posts, only: [:index, :show]
  end

  devise_scope :player do # ゲストプレイヤーログイン用
    post 'player/guest_sign_in', to: 'player/sessions#new_guest'
  end

  # team
  namespace :team do
    resources :teams, only: [:index, :show, :edit, :update, :destroy] do
      get :exit, on: :member # idが必要なためmemberを使う
    end
    resources :posts
    resources :messages, only: [:create]
    resources :rooms, only: [:show, :create]
    end
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  attachment :team_image

  validates :team_image, :category, presence: true
  validates :name, presence: true, length: {maximum: 20}
  validates :member, numericality: :only_integer, length: {maximum: 3} # 数値のみ 3桁まで
  # validates :introduction, presence: true, length: {in: 20..300}
  validates :city, presence: true, length: {in: 2..8}
  validates :street, presence: true, length: {in: 2..20}
  validates :phone_number, numericality: :only_integer, length: {in: 2..20} # 数値のみ

  enum category: {硬式: 0, 軟式: 1}

  def bookmarked_by?(player) # チームに自分(current_player)のブックマークが既にあるか判断する
    bookmarks.where(player_id: player.id).exists? # exists = 存在
  end

  def address
    prefecture_name + city + street
  end

  geocoded_by :address # アドレスを登録した際に緯度、経度のカラムに自動で値を入れてくれる。
  after_validation :geocode #, if: :address_changed? これを書くとエラーが起きる。 # アドレスを変更した際に、自動でgeocodingされる。

  # prefecture_codeからprefecture_nameに変換する
  include JpPrefecture
  jp_prefecture :prefecture_code
  before_validation :set_prefecture_name # 更新前にメソッド(set_prefecture_name)を呼んでset_prefecture_name34行目を実行。

  def set_prefecture_name
    self.prefecture_name = JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  # 今回に限っては必要なかった。
  # def prefecture_name=(prefecture_name)
  #   self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  # end
end

app/controllers/player/teams_controller.rb
class Player::TeamsController < ApplicationController
  before_action :authenticate_player!
  def index
    @q = Team.ransack(params[:q])
    @teams = @q.result(distinct: true).page(params[:page]).per(15).order(:prefecture_code).order(:city).order(member: "DESC")
  end

  def show
    @team = Team.find(params[:id])
    @posts = @team.posts.page(params[:page]).per(10).order(created_at: "DESC")
  end
end

app/controllers/team/confirmations_controller.rb
# frozen_string_literal: true

class Team::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/team/messages_controller.rb
class Team::MessagesController < ApplicationController
  before_action :authenticate_team!, :only => [:create]
  def create
    if Entry.where(:team_id => current_team.id, :room_id => params[:message][:room_id]).present?
       @message = Message.create(params.require(:message).permit(:team_id, :content, :room_id).merge(:team_id => current_team.id))
       redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/team/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Team::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/team/passwords_controller.rb
# frozen_string_literal: true

class Team::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/team/posts_controller.rb
class Team::PostsController < ApplicationController
  before_action :authenticate_team!
  # showを含めるとpostのリンクが機能しなくなってしまうので入れない。
  before_action :protect, only:[:edit, :update, :destroy]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.team_id = current_team.id # この投稿は誰がしたものなのか(今回で言うとチームid)を定義していないと反映されず投稿できない。
    if @post.save
       redirect_to team_post_path(@post), notice: "投稿が完了しました。"
    else
       render "new"
    end
  end

  def index
    @q = Post.ransack(params[:q])
    if params[:team].nil? # 投稿一覧出力時に、チームidが含まれているかどうか。
      @posts = @q.result(distinct: true).page(params[:page]).per(12).order(created_at: "DESC")
    else
      @posts = @q.result(distinct: true).where(team_id: params[:team]).page(params[:page]).per(10).order(created_at: "DESC")
    end
  end

  def show
    @post = Post.find(params[:id])
    # マイページのサイドテーブルのpostリンクが機能しなくなるのでbefore_actionに入れない。
  end

  def edit
  end

  def update
    if @post.update(post_params)
       redirect_to team_post_path, notice: "投稿を編集しました。"
    else
       render "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to team_posts_path, notice: "投稿を削除しました。"
  end

  private

  def protect
    @post = Post.find(params[:id])
    if current_team != @post.team
         redirect_to team_team_path(current_team)
      end
  end

  def post_params
    params.require(:post).permit(:team_id, :title, :body, :post_image)
  end
end

app/controllers/team/registrations_controller.rb
# frozen_string_literal: true

class Team::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    if @team.save # if文を書くことでvalidationもしっかり反映される。ないとエラーが出る。
       NotificationMailer.send_confirm_to_team(@team).deliver
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/team/rooms_controller.rb
class Team::RoomsController < ApplicationController
  before_action :authenticate_team!
  def show
    @room = Room.find(params[:id])
    if Entry.where(:team_id => current_team.id, :room_id => @room.id).present?
       @messages = @room.messages
       @message = Message.new
       @entries = @room.entries
    else
       redirect_back(fallback_location: root_path)
    end
    @room.messages.where(unread: true).each do |message|
      message.update(unread: false)
    end
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :team_id => current_team.id)
    @entry2 = Entry.create(params.require(:entry).permit(:team_id, :room_id).merge(:room_id => @room.id))
    redirect_to team_room_path(@room)
  end
end

app/controllers/team/sessions_controller.rb
# frozen_string_literal: true
class Team::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/team/teams_controller.rb
class Team::TeamsController < ApplicationController
  before_action :authenticate_team!
  before_action :protect, only:[:edit, :update, :destroy]
  def index
    @q = Team.ransack(params[:q])
    @teams = @q.result(distinct: true).page(params[:page]).per(15).order(:prefecture_code).order(:city).order(member: "DESC")
  end

  def show
    @team = Team.find(params[:id])
    @posts = @team.posts.page(params[:page]).per(10).order(created_at: "DESC")
    @currentTeamEntry=Entry.where(team_id: current_team.id)
    @teamEntry=Entry.where(team_id: @team.id)
    if @team.id != current_team.id
       @currentTeamEntry.each do |cu|
         @teamEntry.each do |u|
           if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
           end
         end
       end
       if @isRoom
       else
         @room = Room.new
         @entry = Entry.new
       end
    end
  end

  def edit
  end

  def update
    if @team.update(team_params)
       redirect_to team_team_path(@team), notice: "チーム情報を変更しました。"
    else
       render "edit"
    end
  end

  def exit # 退会画面
  end

  def destroy
    @team.destroy
    redirect_to root_path, notice: "ご利用、ありがとうございました。"
  end

  private

  def protect
    @team = Team.find(params[:id])
    if current_team != @team
       redirect_to team_team_path(current_team)
    end
  end

  def team_params
    params.require(:team).permit(:name, :member, :category, :prefecture_code, :city, :street,
                   :phone_number, :email, :team_image, :introduction)
  end
end

app/controllers/team/unlocks_controller.rb
# frozen_string_literal: true

class Team::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/team/posts_helper.rb
module Team::PostsHelper
end

app/helpers/team/teams_helper.rb
module Team::TeamsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/team/teams/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="page_title">チーム情報編集画面</h1>
    <%= form_for(@team, url: team_team_path) do |f| %>
      <div class="col-xs-6">
        <div class="team_image_edit_area">
          <%= attachment_image_tag @team, :team_image, :fill, 500, 250 %>
          <%= f.attachment_field :team_image, class: "img_attachment" %>
          <%= f.label :introduction, "チーム紹介文", class: "team_info" %>
          <%= f.text_area :introduction, class: "introduction_area" %>
        </div>
      </div>

      <div class="col-xs-6">
        <table class="team_edit_table" width="500">
          <tr>
            <th></th>
            <td class="edit_password">
              <%= link_to "パスワードの変更はこちら", edit_team_registration_path, class: "change_pass_btn" %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :name, "チーム名" %></th>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <th><%= f.label :member, "人数(数字のみ)" %></th>
            <td><%= f.text_field :member %>人</td>
          </tr>
          <tr>
            <th><%= f.label :category, "カテゴリー" %></th>
            <td>
              <%= f.radio_button :category, :硬式 %><%= f.label :category, :硬式 %>
              <%= f.radio_button :category, :軟式 %><%= f.label :category, :軟式 %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :prefecture_code, "都道府県" %></th>
            <td><%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name %></td>
          </tr>
          <tr>
            <th><%= f.label :city, "市区町村" %></th>
            <td><%= f.text_field :city %></td>
          </tr>
          <tr>
            <th><%= f.label :street, "番号・番地" %></th>
            <td><%= f.text_field :street %></td>
          </tr>
          <tr>
            <th><%= f.label :phone_number, "電話番号(ハイフンなし)" %></th>
            <td><%= f.text_field :phone_number %></td>
          </tr>
          <tr>
            <th><%= f.label :email, "メールアドレス" %></th>
            <td><%= f.email_field :email, autocomplete: "email" %></td>
          </tr>
          <tr>
            <td><%= link_to "退会する", exit_team_team_path, class: "btn exit_btn" %></td>
            <td><%= f.submit "変更内容を保存する", class: "btn update_btn" %></td>
          </tr>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/team/teams/exit.html.erb
<div class="exit_page">
  <h1><strong>本当に退会しますか？</strong></h1>
  <h2>
    退会すると、会員登録情報を削除し、<br>
    投稿や閲覧ができなくなります。<br>
    退会する場合は、「退会する」をクリックしてください。
  </h2>
  <%= link_to "退会しない", team_team_path, class: "btn no_exit_btn" %>
  <%= link_to "退会する", team_team_path, class: "btn exit_btn", method: :delete, "data-confirm" => "退会してよろしいですか？" %>
</div>

app/views/team/teams/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <h1 class="page_title">チーム一覧</h1>
    </div>
    <div class="col-xs-3">
      <%= search_form_for @q, url: team_teams_path, class: "seach" do |f| %>
        <%= f.search_field :name_or_prefecture_name_or_city_cont, class: "seach_form", placeholder: "検索" %><br>
        <%= f.number_field :member_gteq, class: "seach_member_form" %>人以上
        <%= f.number_field :member_lt, class: "seach_member_form" %>人未満<br>
        <%= f.radio_button :category_eq, '', {:checked => true} %>指定なし
        <%= f.radio_button :category_eq, 0 %>硬式
        <%= f.radio_button :category_eq, 1 %>軟式
        <%= button_tag type: "submit" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="team_boxes">
    <% @teams.each do |team| %>
      <div class="team_box">
        <%= team.prefecture_name %>
        <% if team == current_team %>
          <%= link_to edit_team_team_path(current_team) do %>
            <i class="fas fa-baseball-ball"></i>
          <% end %>
        <% end %><br>
        <%= link_to team_team_path(team) do %>
          <%= attachment_image_tag team, :team_image, :fill, 200, 130 %><br>
          <p class="team_box_name"><%= team.name %></p>
        <% end %>
        <div class="team_box_bottom">
          ・<%= team.city %><br>
          ・<%= team.category %><br>
          ・<%= team.member %>人
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/team/teams/show.html.erb
<div class="container">
  <div class="row">
    <% if @team == current_team %>
      <h1 class="page_title">マイチーム
        <%= link_to edit_team_team_path(@team) do %>
          <i class="fa fa-cog"> 編集する</i>
        <% end %>
      </h1>
    <% end %>
    <p class="flash_message"><%= flash[:notice] %></p>
    <div class="col-xs-3 side_posts">
      <table width="350" class="side_table">
        <thead>
          <% if @team == current_team %>
            <tr>
              <th colspan="3">新着情報</th> <!-- 3つ分のスペースを結合 -->
            </tr>
          <% else %>
            <tr>
              <th colspan="2"><%= @team.name %>　新着情報</th>
            </tr>
          <% end %>
        </thead>
        <% @posts.each do |post| %>
          <% if @team == current_team %>
            <% if @team.prefecture_name == post.team.prefecture_name %>
            <!-- prefecture_codeをprefecture_nameに変換しているため -->
              <tbody>
                <tr>
                  <td><%= post.created_at.strftime("%Y/%m/%d") %></td>
                  <td ><%= link_to post.title, team_post_path(post), class: "post_title" %></td>
                  <td><%= post.team.name %></td>
                </tr>
              </tbody>
            <% end %>
          <% else %>
            <% if @team == post.team %>
              <tbody>
                <tr>
                  <td><%= post.created_at.strftime("%Y/%m/%d") %></td>
                  <td><%= link_to post.title, team_post_path(post), class: "post_title" %></td>
                </tr>
              </tbody>
            <% end %>
          <% end %>
        <% end %>
      </table>
      <%= link_to "#{@team.name}の投稿一覧へ", team_posts_path(team: @team.id), class: "post_index_path" %> <!-- teamのidを含む -->
    </div>
    <div class="col-xs-9">
      <div class="team_information">
        <div class="information_top">
          <h3><%= @team.category %></h3>
          <h2><%= @team.name %></h2>
          <h3><%= @team.member %>人</h3>
        </div>
        <div class="team_image">
          <%= attachment_image_tag @team, :team_image, :fill, 900, 600 %>
        </div>
        <p class="team_introduction"><%= safe_join(@team.introduction.split("\n"), tag(:br)) %></p>
        <!-- safe_joinによって改行が反映される -->
        <table width="350" class="address_table">
          <tr>
            <th><i class="fas fa-mobile-alt fa-fw"></i> 連絡先</th>
            <!-- クラスにfa-fwを追加するとアイコンの横幅が統一される -->
            <td><%= @team.phone_number %></td>
          </tr>
          <tr>
            <th><i class="fas fa-baseball-ball fa-fw"></i> 住所</th>
            <!-- クラスにfa-fwを追加するとアイコンの横幅が統一される -->
            <td><%= @team.prefecture_name %><%= @team.city %><%= @team.street %></td>
            <!-- prefecture_codeをprefecture_nameに変換しているため -->
          </tr>
        </table>
        <div id="map"></div>
      </div>
      <% if @team.id != current_team.id %>
        <% if @isRoom == true %>
          <%= link_to team_room_path(@roomId) do %>
            <i class="fas fa-paper-plane"> チャットへ...</i>
          <% end %>
        <% else %>
          <%= form_for(@room, url: team_rooms_path) do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :team_id, :value=> @team.id %>
            <% end %>
            <%= f.submit "チャットを始める", class: "chats_btn" %>
          <% end %>
        <% end %>
      <% end %>
      <% if @team != current_team %>
        <%= link_to "前の画面へ戻る", :back, class: "back_btn" %> <!-- 前の状態の画面に戻る -->
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  let map
  let geocoder
  function initMap() {
  // latitude,longitudeから位置を特定
      var test ={lat: <%= @team.latitude %>, lng: <%= @team.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 15,
                center: test
      });
      var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);
      var contentString = '住所：<%= @team.prefecture_name %><%= @team.city %><%= @team.street %>';
      // prefecture_codeをprefecture_nameに変換しているため
      var infowindow = new google.maps.InfoWindow({
        content: contentString
      });

   // Map上の指定した位置にピンを挿して表示する
      var marker = new google.maps.Marker({
      position:test,
      map: map,
      title: contentString
      });

      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['API_KEY'] %>&callback=initMap" async defer>
</script>