config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: {
    sessions: 'player/sessions',
    registrations: 'player/registrations',
    passwords: 'player/passwords'
  }

  devise_for :teams, controllers: {
    sessions: 'team/sessions',
    registrations: 'team/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # player
  root 'player/home#about' # ネストしたコントローラに対してrootを設定する記述法
  namespace :player do
    resources :players, only: [:show, :edit, :update, :destroy] do
      get :exit, on: :member # idが必要なためmemberを使う
    end
    resources :teams, only: [:index, :show] do
      resources :contacts, only: [:new, :create] do
        get :complete, on: :collection # idがないからcollectionを使う
      end
      resource :bookmarks, only: [:create, :destroy] # この２つはid不要。
    end
    resources :bookmarks, only: [:index] # 上に混ぜるとpathが消えるので分けた。
    resources :posts, only: [:index, :show]
  end

  devise_scope :player do # ゲストプレイヤーログイン用
    post 'player/guest_sign_in', to: 'player/sessions#new_guest'
  end

  # team
  namespace :team do
    resources :teams, only: [:index, :show, :edit, :update, :destroy] do
      get :exit, on: :member # idが必要なためmemberを使う
    end
    resources :posts
    resources :messages, only: [:create]
    resources :rooms, only: [:show, :create]
    end
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookmarks, dependent: :destroy
  has_many :contacts, dependent: :destroy

  validates :name, presence: true, length: {maximum: 15}

  # prefecture_codeからprefecture_nameに変換する
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    self.prefecture_name = JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
      self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # ゲストプレイヤーの登録条件
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |player|
      player.name = SecureRandom.urlsafe_base64(5)
      player.prefecture_name = "埼玉県" # 今回は1番チーム登録の多い埼玉県を採用
      player.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/player/bookmarks_controller.rb
class Player::BookmarksController < ApplicationController
  before_action :authenticate_player!
  def index
    @player = current_player
      @bookmarks = Bookmark.joins(:team).where(player_id: @player.id).order(:prefecture_code).order(:city).order(member: "DESC")
      # .joins(:team)により、bookmark/indexでも、teamカラムの条件(cityなど)が使えるようになる。
  end

  def create
    @team = Team.find(params[:team_id])
    @bookmark = current_player.bookmarks.new(team_id: @team.id)
    @bookmark.save
    # 非同期通信採用のため、redirect不要。
  end

  def destroy
    @team = Team.find(params[:team_id])
    @bookmark = current_player.bookmarks.find_by(team_id: @team.id)
    @bookmark.destroy
    # 非同期通信採用のため、redirect不要。
  end
end

app/controllers/player/confirmations_controller.rb
# frozen_string_literal: true

class Player::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/player/contacts_controller.rb
class Player::ContactsController < ApplicationController
  before_action :authenticate_player!
  def new
    @contact = Contact.new
    @team = Team.find(params[:team_id])
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.player_id = current_player.id
    @team = Team.find(params[:team_id])
    if @contact.save
       ContactMailer.contact_mail(@contact).deliver
       redirect_to complete_player_team_contacts_path(team_id: @team.id)
    else
       render "new"
    end
  end

  def complete # 送信完了画面
    @team = Team.find(params[:team_id])
    # オススメチームの表示↓↓
    @i = current_player.contacts
    @all = Team.all
    @i.each do |team|
      @all = @all.where.not(id: team.team_id)
    end
    @picup_team = @all.order("RAND()").limit(3)
  end

  private

  def contact_params
    params.require(:contact).permit(:player_id, :team_id, :name, :school, :year, :address,
                                    :phone_number, :choice, :day, :question)
  end
end

app/controllers/player/home_controller.rb
class Player::HomeController < ApplicationController
  def about
  end
end

app/controllers/player/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Player::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/player/passwords_controller.rb
# frozen_string_literal: true

class Player::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/player/players_controller.rb
class Player::PlayersController < ApplicationController
  before_action :authenticate_player!
  before_action :protect, only:[:edit, :update, :destroy]
  def show
    @player = current_player
    @teams = Team.where(prefecture_code: @player.prefecture_code).page(params[:page]).per(12).order(:city).order(member: "DESC")
    # @teams = Team.page(params[:page]).per(8).order(:prefecture_code).order(:city).order(member: "DESC")
    # 7行目でも出力できたが、6行目の方が確実？ (current_playerと同じ都道府県テームの出力。一応viewにも定義はしてある。)
    @posts = Post.page(params[:page]).per(10).order(created_at: "DESC")
    # @posts = Post.joins(:team).where(prefecture_code: @player.prefecture_code).page(params[:page]).per(8).order(:prefecture_code).order(created_at: "DESC")
    # @teamsと同じようにできない？
  end

  def edit
  end

  def update
    if @player.update(player_params)
       redirect_to player_player_path(@player), notice: "登録情報を変更しました。"
    else
       render "edit"
    end
  end

  def exit # 退会画面
  end

  def destroy
    @player.destroy
    redirect_to root_path, notice: "ご利用、ありがとうございました。"
  end

  private

  def protect
    @player = Player.find(params[:id])
    if current_player != @player
         redirect_to player_player_path(current_player)
      end
  end

  def player_params
    params.require(:player).permit(:name, :prefecture_code, :email)
  end
end

app/controllers/player/posts_controller.rb
class Player::PostsController < ApplicationController
  before_action :authenticate_player!
  def index
    @q = Post.ransack(params[:q])
    if params[:team].nil? # 投稿一覧出力時に、チームidが含まれているかどうか。
      @posts = @q.result(distinct: true).page(params[:page]).per(12).order(created_at: "DESC")
    else
      @posts = @q.result(distinct: true).where(team_id: params[:team]).page(params[:page]).per(10).order(created_at: "DESC")
    end
  end

  def show
    @post = Post.find(params[:id])
    @posts = @post.team.posts.page(params[:page]).per(10).order(created_at: "DESC")
    # 投稿チームのpostsを表示。
  end
end

app/controllers/player/registrations_controller.rb
# frozen_string_literal: true

class Player::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: [:update, :destroy]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    if @player.save # if文を書くことでvalidationもしっかり反映される。ないとエラーが出る。
       NotificationMailer.send_confirm_to_player(@player).deliver
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/player/sessions_controller.rb
# frozen_string_literal: true

class Player::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  def new_guest
    player = Player.guest
    sign_in player
    redirect_to player_player_path(current_player), notice: "ゲストプレイヤーとしてログインしました。"
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/player/teams_controller.rb
class Player::TeamsController < ApplicationController
  before_action :authenticate_player!
  def index
    @q = Team.ransack(params[:q])
    @teams = @q.result(distinct: true).page(params[:page]).per(15).order(:prefecture_code).order(:city).order(member: "DESC")
  end

  def show
    @team = Team.find(params[:id])
    @posts = @team.posts.page(params[:page]).per(10).order(created_at: "DESC")
  end
end

app/controllers/player/unlocks_controller.rb
# frozen_string_literal: true

class Player::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/team/confirmations_controller.rb
# frozen_string_literal: true

class Team::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/team/messages_controller.rb
class Team::MessagesController < ApplicationController
  before_action :authenticate_team!, :only => [:create]
  def create
    if Entry.where(:team_id => current_team.id, :room_id => params[:message][:room_id]).present?
       @message = Message.create(params.require(:message).permit(:team_id, :content, :room_id).merge(:team_id => current_team.id))
       redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/team/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Team::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/team/passwords_controller.rb
# frozen_string_literal: true

class Team::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/team/posts_controller.rb
class Team::PostsController < ApplicationController
  before_action :authenticate_team!
  # showを含めるとpostのリンクが機能しなくなってしまうので入れない。
  before_action :protect, only:[:edit, :update, :destroy]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.team_id = current_team.id # この投稿は誰がしたものなのか(今回で言うとチームid)を定義していないと反映されず投稿できない。
    if @post.save
       redirect_to team_post_path(@post), notice: "投稿が完了しました。"
    else
       render "new"
    end
  end

  def index
    @q = Post.ransack(params[:q])
    if params[:team].nil? # 投稿一覧出力時に、チームidが含まれているかどうか。
      @posts = @q.result(distinct: true).page(params[:page]).per(12).order(created_at: "DESC")
    else
      @posts = @q.result(distinct: true).where(team_id: params[:team]).page(params[:page]).per(10).order(created_at: "DESC")
    end
  end

  def show
    @post = Post.find(params[:id])
    # マイページのサイドテーブルのpostリンクが機能しなくなるのでbefore_actionに入れない。
  end

  def edit
  end

  def update
    if @post.update(post_params)
       redirect_to team_post_path, notice: "投稿を編集しました。"
    else
       render "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to team_posts_path, notice: "投稿を削除しました。"
  end

  private

  def protect
    @post = Post.find(params[:id])
    if current_team != @post.team
         redirect_to team_team_path(current_team)
      end
  end

  def post_params
    params.require(:post).permit(:team_id, :title, :body, :post_image)
  end
end

app/controllers/team/registrations_controller.rb
# frozen_string_literal: true

class Team::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
    if @team.save # if文を書くことでvalidationもしっかり反映される。ないとエラーが出る。
       NotificationMailer.send_confirm_to_team(@team).deliver
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/views/player/teams/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <h1 class="page_title">チーム一覧</h1>
    </div>
    <div class="col-xs-3">
      <%= search_form_for @q, url: player_teams_path, class: "seach" do |f| %>
        <%= f.search_field :name_or_prefecture_name_or_city_cont, class: "seach_form", placeholder: "検索" %><br>
        <%= f.number_field :member_gteq, class: "seach_member_form" %>人以上
        <%= f.number_field :member_lt, class: "seach_member_form" %>人未満<br>
        <%= f.radio_button :category_eq, '', {:checked => true} %>指定なし
        <%= f.radio_button :category_eq, 0 %>硬式
        <%= f.radio_button :category_eq, 1 %>軟式
        <%= button_tag type: "submit" do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="team_boxes">
    <% @teams.each do |team| %>
      <div class="team_box">
        <div id="bookmarks_buttons_<%= team.id %>">
          <%= render partial: 'player/bookmarks/bookmark', locals: { team: team } %>
        </div>
        <%= link_to player_team_path(team) do %>
          <%= attachment_image_tag team, :team_image, :fill, 200, 130 %><br>
          <p class="team_box_name"><%= team.name %></p>
        <% end %>
        <div class="team_box_bottom">
          ・<%= team.prefecture_name %><%= team.city %><br>
          ・<%= team.category %><br>
          ・<%= team.member %>人
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/player/teams/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3 side_posts">
      <table width="350" class="side_table">
        <thead>
          <tr>
            <th colspan="2"><%= @team.name %>　新着情報</th> <!-- 2つ分のスペースを結合 -->
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <% if @team == post.team %>
              <tr>
                <td><%= post.created_at.strftime("%Y/%m/%d") %></td>
                <td><%= link_to post.title, player_post_path(post), class: "post_title" %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <%= link_to "#{@team.name}の投稿一覧へ", player_posts_path(team: @team.id), class: "post_index_path" %> <!-- teamのidを含む -->
    </div>
    <div class="col-xs-9">
      <div class="team_information">
        <ul class="player_teams_information_top">
          <li id="bookmarks_buttons_<%= @team.id %>">
            <%= render partial: 'player/bookmarks/bookmark', locals: { team: @team } %>
          </li>
          <li class="category"><%= @team.category %></li>
          <li class="name"><%= @team.name %></li>
          <li class="member"><%= @team.member %>人</li>
          <li>
              <%= link_to new_player_team_contact_path(@team) do %>
                <i class="far fa-envelope"> お問い合わせ</i>
              <% end %>
          </li>
        </ul>
        <div class="team_image">
          <%= attachment_image_tag @team, :team_image, :fill, 900, 500 %>
        </div>
        <p class="team_introduction"><%= safe_join(@team.introduction.split("\n"), tag(:br)) %></p>
        <!-- safe_joinによって改行が反映される -->
        <table width="350" class="address_table">
          <tr>
            <th><i class="fas fa-mobile-alt fa-fw"></i> 連絡先</th>
            <!-- クラスにfa-fwを追加するとアイコンの横幅が統一される -->
            <td><%= @team.phone_number %></td>
          </tr>
          <tr>
            <th><i class="fas fa-baseball-ball fa-fw"></i> 住所</th>
            <!-- クラスにfa-fwを追加するとアイコンの横幅が統一される -->
            <td><%= @team.prefecture_name %><%= @team.city %><%= @team.street %></td>
            <!-- prefecture_codeをprefecture_nameに変換しているため -->
          </tr>
        </table>
        <div id="map"></div>
      </div>
      <%= link_to "前の画面へ戻る", :back, class: "back_btn" %> <!-- 前の状態の画面に戻る -->
    </div>
  </div>
</div>

<script type="text/javascript">
  function initMap() {
// latitude,longitudeから位置を特定
    var test ={lat: <%= @team.latitude %>, lng: <%= @team.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    var contentString = '住所：<%= @team.prefecture_name %><%= @team.city %><%= @team.street %>';
    // prefecture_codeをprefecture_nameに変換しているため
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

 // Map上の指定した位置にピンを挿して表示する
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['API_KEY'] %>&callback=initMap" async defer>
</script>