config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: {
    sessions: 'player/sessions',
    registrations: 'player/registrations',
    passwords: 'player/passwords'
  }

  devise_for :teams, controllers: {
    sessions: 'team/sessions',
    registrations: 'team/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # player
  root 'player/home#about' # ネストしたコントローラに対してrootを設定する記述法
  namespace :player do
    resources :players, only: [:show, :edit, :update, :destroy] do
      get :exit, on: :member # idが必要なためmemberを使う
    end
    resources :teams, only: [:index, :show] do
      resources :contacts, only: [:new, :create] do
        get :complete, on: :collection # idがないからcollectionを使う
      end
      resource :bookmarks, only: [:create, :destroy] # この２つはid不要。
    end
    resources :bookmarks, only: [:index] # 上に混ぜるとpathが消えるので分けた。
    resources :posts, only: [:index, :show]
  end

  devise_scope :player do # ゲストプレイヤーログイン用
    post 'player/guest_sign_in', to: 'player/sessions#new_guest'
  end

  # team
  namespace :team do
    resources :teams, only: [:index, :show, :edit, :update, :destroy] do
      get :exit, on: :member # idが必要なためmemberを使う
    end
    resources :posts
    resources :messages, only: [:create]
    resources :rooms, only: [:show, :create]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :player
  belongs_to :team

  #ひとりが１チームに対して１つしかブックマークをつけられないようにする
  validates_uniqueness_of :team_id, scope: :player_id

  def bookmarked_by?(player) # チームに自分(current_player)のブックマークが既にあるか判断する
            bookmarks.where(player_id: player.id).exists? # exists = 存在
    end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :player
  belongs_to :team

  validates :name, presence: true
  validates :year, presence: true
  validates :choice, presence: true
  validates :question, length: {maximum: 100}

  enum choice: {入団希望: 0, 体験希望: 1}
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :team
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :team
  belongs_to :room

  validates :content, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookmarks, dependent: :destroy
  has_many :contacts, dependent: :destroy

  validates :name, presence: true, length: {maximum: 15}

  # prefecture_codeからprefecture_nameに変換する
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    self.prefecture_name = JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
      self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # ゲストプレイヤーの登録条件
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |player|
      player.name = SecureRandom.urlsafe_base64(5)
      player.prefecture_name = "埼玉県" # 今回は1番チーム登録の多い埼玉県を採用
      player.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :team
  attachment :post_image

  validates :title, presence: true
    validates :body, presence: true, length: {maximum: 300}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  attachment :team_image

  validates :team_image, :category, presence: true
  validates :name, presence: true, length: {maximum: 20}
  validates :member, numericality: :only_integer, length: {maximum: 3} # 数値のみ 3桁まで
  # validates :introduction, presence: true, length: {in: 20..300}
  validates :city, presence: true, length: {in: 2..8}
  validates :street, presence: true, length: {in: 2..20}
  validates :phone_number, numericality: :only_integer, length: {in: 2..20} # 数値のみ

  enum category: {硬式: 0, 軟式: 1}

  def bookmarked_by?(player) # チームに自分(current_player)のブックマークが既にあるか判断する
    bookmarks.where(player_id: player.id).exists? # exists = 存在
  end

  def address
    prefecture_name + city + street
  end

  geocoded_by :address # アドレスを登録した際に緯度、経度のカラムに自動で値を入れてくれる。
  after_validation :geocode #, if: :address_changed? これを書くとエラーが起きる。 # アドレスを変更した際に、自動でgeocodingされる。

  # prefecture_codeからprefecture_nameに変換する
  include JpPrefecture
  jp_prefecture :prefecture_code
  before_validation :set_prefecture_name # 更新前にメソッド(set_prefecture_name)を呼んでset_prefecture_name34行目を実行。

  def set_prefecture_name
    self.prefecture_name = JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  # 今回に限っては必要なかった。
  # def prefecture_name=(prefecture_name)
  #   self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    case resource
    when Player
      player_player_path(current_player)
    when Team
      team_team_path(current_team)
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :player
       root_path
    when :team
       root_path
    end
  end

  def after_sign_up_path_for(resource)
    case resource
    when Player
       player_player_path(current_player)
    when Team
       team_team_path(current_team)
    end
  end

  # ゲストプレイヤーの削除、パスワード変更などを制限する。
  def check_guest
    email = resource&.email || params[:player][:email].downcase
    if email == "guest@example.com"
      redirect_to player_player_path(current_player), alert: "ゲストプレイヤーの変更・削除はできません。"
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :member, :team_image, :introduction,
      :prefecture_code, :city, :street, :phone_number, :category, :email, :encrypted_password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/team/posts_helper.rb
module Team::PostsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseMatch</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="responsive.scss">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="wrapper"> <!-- フッターを最下位で固定するために親要素を追加 -->
      <header>
        <div class="container">
          <div class="header_logo"><strong>B</strong>aseMatch</div>
          <nav>
            <ul class="nav_list">
              <% if player_signed_in? %>
                <li>
                  <%= link_to "当サイトについて", root_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "マイページ", player_player_path(current_player), class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "チーム一覧", player_teams_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "投稿一覧", player_posts_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "お気に入り", player_bookmarks_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_player_session_path, class: "nav_list_item", method: :delete %>
                </li>
              <% elsif team_signed_in? %>
                <li>
                  <%= link_to "当サイトについて", root_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "マイチーム", team_team_path(current_team), class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "新規投稿", new_team_post_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "チーム一覧", team_teams_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "投稿一覧", team_posts_path, class: "nav_list_item" %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_team_session_path, class: "nav_list_item", method: :delete %>
                </li>
              <% else %>
                <li>
                  <%= link_to "当サイトについて", root_path, class: "nav_list_item" %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer>
        <section id="about_contact">
          <h1 class="footer_section_title">Contact</h1>
          <div class="contact_area">
            <div class="contact_left">
              <table width="350" class="footer_table">
                <tr>
                  <th>Email</th>
                  <td>xxx@xxx.com</td>
                </tr>
                <tr>
                  <th>Tell</th>
                  <td>080-xxxx-xxxx</td>
                </tr>
              </table>
            </div>
            <div class="contact_right">
              <span class="insta">
                <i class="fab fa-instagram"></i>
              </span>
              <i class="fab fa-twitter"></i>
              <i class="fab fa-facebook-f"></i>
            </div>
          </div>
        </section>
      </footer>
    </div>
  </body>
</html>